use_frameworks!

target 'FormValidators_Example' do
  pod 'FormValidators', :path => '../'

  target 'FormValidators_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
